### ISSUE TITLE
Old games don't show raw scores

### ISSUE THREAD

**Issue by JMCanning78** [BlaiseRitchie/MahjongSite#23]
If you go to the older games in the game history, they appear to show the final score but the raw score field is 0.  For example see games with ID < 579 (although ID 578 looks OK):
https://seattlemahjong.club/history/39
When you try to edit them, the raw scores are not carried into the dialog, for example:
https://seattlemahjong.club/admin/edit/446

Perhaps this is a legacy issue due to a change in schema that added the raw score at some point in time.

**Comment by BlaiseRideout** [comment]
This is a legacy issue because we didn't used to record the raw score and I imported all the old score data from the previous score keeping website.
